set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]

set_property IOSTANDARD LVCMOS18 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports in0_out]
set_property IOSTANDARD LVCMOS18 [get_ports in0_and_in1_out]
set_property IOSTANDARD LVCMOS18 [get_ports in0_or_in1_out]
set_property IOSTANDARD LVCMOS18 [get_ports not_in2_out]
set_property IOSTANDARD LVCMOS18 [get_ports clk_1point5hz]
set_property PACKAGE_PIN AD10 [get_ports {in[0]}]
set_property PACKAGE_PIN AE8 [get_ports {in[1]}]
set_property PACKAGE_PIN AF9 [get_ports {in[2]}]
set_property PACKAGE_PIN AF8 [get_ports {in[3]}]
set_property PACKAGE_PIN AE10 [get_ports {in[4]}]
set_property PACKAGE_PIN AP8 [get_ports in0_out]
set_property PACKAGE_PIN H23 [get_ports in0_and_in1_out]
set_property PACKAGE_PIN P20 [get_ports in0_or_in1_out]
set_property PACKAGE_PIN P21 [get_ports not_in2_out]
set_property PACKAGE_PIN P23 [get_ports clk_1point5hz]

set_property IOSTANDARD LVDS [get_ports {osc_300_pn[0]}]
set_property IOSTANDARD LVDS [get_ports {osc_300_pn[1]}]
set_property PACKAGE_PIN AK17 [get_ports {osc_300_pn[0]}]

create_clock -period 3.333 -name {osc_300_pn[0]} -waveform {0.000 1.667} [get_ports {osc_300_pn[0]}]
